apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-stack
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/flux-cluster/flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
